# WRDS OptionMetrics Data Queries

Includes BTC options end of day info

In [1]:
import pandas as pd
import numpy as np
import quandl
import wrds

In [2]:
BrianBoonstraPrivateKeys['wrds']['username']

'boonstra2022'

The following password-free login depends on having created a `~/.pgpass` file with with WRDS entries, as in 

```
wrds-pgdata.wharton.upenn.edu:9737:wrds:brianboonstra:<password>
```

In [3]:
db = wrds.Connection(
    wrds_username=BrianBoonstraPrivateKeys['wrds']['username'],
)

Loading library list...
Done

In [4]:
db.list_libraries()

['aha_sample',
 'ahasamp',
 'audit',
 'audit_acct_os',
 'audit_audit_comp',
 'audit_common',
 'audit_corp_legal',
 'auditsmp',
 'auditsmp_all',
 'bank',
 'bank_all',
 'bank_premium_samp',
 'banksamp',
 'block',
 'block_all',
 'boardex_trial',
 'boardsmp',
 'bvd',
 'bvd_ama_large',
 'bvd_ama_medium',
 'bvd_ama_small',
 'bvd_ama_verylarge',
 'bvd_amadeus_trial',
 'bvd_bvdbankf_trial',
 'bvd_orbis_large',
 'bvd_orbis_medium',
 'bvd_orbis_small',
 'bvd_orbis_trial',
 'bvdsamp',
 'calcbench_trial',
 'calcbnch',
 'cboe',
 'cboe_all',
 'cboe_sample',
 'cboesamp',
 'ciq',
 'ciq_capstrct',
 'ciq_common',
 'ciq_ratings',
 'ciq_transactions',
 'ciq_transcripts',
 'ciqsamp',
 'ciqsamp_capstrct',
 'ciqsamp_common',
 'ciqsamp_keydev',
 'ciqsamp_pplintel',
 'ciqsamp_ratings',
 'ciqsamp_transactions',
 'ciqsamp_transcripts',
 'cisdmsmp',
 'columnar',
 'comp',
 'comp_bank',
 'comp_bank_daily',
 'comp_emdb_daily',
 'comp_emdb_monthly',
 'comp_execucomp',
 'comp_global',
 'comp_global_daily',
 'comp_na_annual_all',
 'comp_na_daily_all',
 'comp_na_monthly_all',
 'comp_ph',
 'comp_ratings',
 'comp_segments_hist',
 'comp_segments_hist_daily',
 'comp_snapshot',
 'compa',
 'compb',
 'compg',
 'comph',
 'compm',
 'compsamp',
 'compsamp_all',
 'compsamp_snapshot',
 'compseg',
 'compsnap',
 'contrib',
 'contrib_as_filed_financials',
 'contrib_ceo_turnover',
 'contrib_char_returns',
 'contrib_general',
 'contrib_global_factor',
 'contrib_green_returns',
 'contrib_intangible_value',
 'contrib_kpss',
 'contrib_liva',
 'crsp',
 'crsp_a_ccm',
 'crsp_a_indexes',
 'crsp_a_stock',
 'crsp_a_stock62',
 'crsp_a_treasuries',
 'crsp_a_ziman',
 'crsp_m_ccm',
 'crsp_m_indexes',
 'crsp_m_stock',
 'crsp_m_stock62',
 'crsp_m_treasuries',
 'crsp_m_ziman',
 'crsp_q_ccm',
 'crsp_q_indexes',
 'crsp_q_indexhist',
 'crsp_q_mutualfunds',
 'crsp_q_stock',
 'crsp_q_stock62',
 'crsp_q_treasuries',
 'crsp_q_ziman',
 'crspm',
 'crspq',
 'crspsamp',
 'crspsamp_all',
 'crspsamp_mf',
 'csmar',
 'csmar_financial',
 'csmar_funds',
 'csmar_hld',
 'csmar_trade',
 'csmsamp_all',
 'dealscan',
 'djones',
 'djones_all',
 'dmef',
 'dmef_all',
 'doe',
 'doe_all',
 'emdb',
 'etfg',
 'etfg_analytics',
 'etfg_constituents',
 'etfg_fund_flow',
 'etfg_industry',
 'etfg_samp',
 'etfgsamp',
 'eurekahedge_sample',
 'eursamp',
 'execcomp',
 'factsamp_all',
 'factsamp_revere',
 'ff',
 'ff_all',
 'fisd',
 'fisd_common',
 'fisd_fisd',
 'fisd_naic',
 'fisdsamp',
 'fisdsamp_all',
 'fjc',
 'fjc_linking',
 'fjc_litigation',
 'frb',
 'frb_all',
 'fssamp',
 'ftsesamp',
 'ftsesamp_russell_us',
 'gutenberg',
 'hfrsamp',
 'hfrsamp_hfrdb',
 'ibes',
 'ibessamp_kpi',
 'ifgrsamp',
 'ims_obp_trial',
 'imssamp',
 'infogroupsamp_business',
 'infogroupsamp_residential',
 'insdsamp',
 'iri',
 'iri_all',
 'iss',
 'iss_incentive_lab',
 'iss_incentive_lab_europe',
 'iss_va_mf',
 'iss_va_shareholder',
 'iss_va_vote_us',
 'issm',
 'issm_nasd1987',
 'issm_nasd1988',
 'issm_nasd1989',
 'issm_nasd1990',
 'issm_nasd1991',
 'issm_nasd1992',
 'issm_nyam1983',
 'issm_nyam1984',
 'issm_nyam1985',
 'issm_nyam1986',
 'issm_nyam1987',
 'issm_nyam1988',
 'issm_nyam1989',
 'issm_nyam1990',
 'issm_nyam1991',
 'issm_nyam1992',
 'kld',
 'kld_histall',
 'kpisamp',
 'ktmine_patents_samp',
 'ktsamp',
 'lvnsamp',
 'lvnsamp_all',
 'macrofin',
 'macrofin_comm_trade',
 'markit',
 'markit_cds',
 'markit_msf_analytics_eqty_amer',
 'markit_red',
 'mfl',
 'mflinks_all',
 'midas',
 'morningstarsamp_cisdm',
 'mrktsamp',
 'mrktsamp_cds',
 'mrktsamp_cdx',
 'mrktsamp_msf',
 'msci_esg_samp',
 'msciesmp',
 'msfanly',
 'msrb',
 'msrb_all',
 'msrbsamp',
 'msrbsamp_all',
 'omtrial',
 'optionm',
 'optionm_all',
 'optionmsamp_europe',
 'optionmsamp_us',
 'otc',
 'otc_endofday',
 'phlx',
 'phlx_all',
 'pitchsmp',
 'ppubsamp',
 'ppubsamp_d4d',
 'ppubsamp_rx_checkup',
 'preqin',
 'preqin_cashflow',
 'preqin_deals',
 'preqin_gp',
 'preqin_lp',
 'preqin_pe',
 'preqin_vc',
 'preqsamp',
 'preqsamp_all',
 'public',
 'public_all',
 'pwt',
 'pwt_all',
 'ravenpack_trial',
 'reprisk',
 'reprisk_sample',
 'reprisk_v2',
 'repsamp',
 'revelio',
 'revelio_common',
 'revelio_individual',
 'revelio_job_postings',
 'revelio_samp',
 'revelio_workforce_dynamics',
 'revsamp',
 'risk',
 'risk_directors',
 'risk_governance',
 'risk_proposals',
 'risk_votes',
 'risksamp',
 'risksamp_all',
 'rpnasamp',
 'rq_all',
 'rstat_samp',
 'rstatsmp',
 'sdc',
 'sdcsamp',
 'secsamp',
 'secsamp_all',
 'snapsamp',
 'snlsamp',
 'snlsamp_fig',
 'sp_esg',
 'sprat',
 'sustain',
 'sustainalytics_all',
 'sustainalyticssamp_all',
 'sustsamp',
 'taqm_2003',
 'taqm_2004',
 'taqm_2005',
 'taqm_2006',
 'taqm_2007',
 'taqm_2008',
 'taqm_2009',
 'taqm_2010',
 'taqm_2011',
 'taqm_2012',
 'taqm_2013',
 'taqm_2014',
 'taqm_2015',
 'taqm_2016',
 'taqm_2017',
 'taqm_2018',
 'taqm_2019',
 'taqm_2020',
 'taqm_2021',
 'taqm_2022',
 'taqm_2023',
 'taqm_2024',
 'taqmsamp',
 'taqmsamp_all',
 'taqmsec',
 'taqsamp',
 'taqsamp_all',
 'tass',
 'tfn',
 'totalq',
 'totalq_all',
 'tr_13f',
 'tr_common',
 'tr_dealscan',
 'tr_ds_comds',
 'tr_ds_econ',
 'tr_ds_equities',
 'tr_ds_fut',
 'tr_esg',
 'tr_ibes',
 'tr_ibes_guidance',
 'tr_insiders',
 'tr_mutualfunds',
 'tr_sdc_ma',
 'tr_sdc_ni',
 'tr_sdc_samples',
 'tr_tass',
 'tr_worldscope',
 'trace',
 'trace_enhanced',
 'trace_standard',
 'trcommon',
 'trcstsmp',
 'trdbdmismp',
 'trdbwbsmp',
 'trdssamp',
 'trdstrm',
 'tresg',
 'tresgsmp',
 'trsamp',
 'trsamp_all',
 'trsamp_db_dmi',
 'trsamp_db_wb',
 'trsamp_ds_eq',
 'trsamp_dscom',
 'trsamp_dsecon',
 'trsamp_dsfut',
 'trsamp_esg',
 'trsamp_sdc_ma',
 'trsamp_sdc_ni',
 'trsamp_worldscope',
 'trucost',
 'trucost_carbon',
 'trucost_common',
 'trucost_environ',
 'trucost_fossilfuel',
 'trucost_paris',
 'trucost_risk',
 'trucost_samp',
 'trucost_sector_ff',
 'trucost_sector_revenue',
 'trws',
 'twoiq_samp',
 'twoiqsmp',
 'wappsamp',
 'wenvsmp',
 'wmfsmp',
 'wrds_environmental_samp',
 'wrds_insiders_samp',
 'wrds_lib_internal',
 'wrds_mutualfund_samp',
 'wrds_sec_search',
 'wrdsapps',
 'wrdsapps_backtest_basic',
 'wrdsapps_backtest_plus',
 'wrdsapps_bondret',
 'wrdsapps_eushort',
 'wrdsapps_evtstudy_int',
 'wrdsapps_evtstudy_lr',
 'wrdsapps_evtstudy_us',
 'wrdsapps_finratio',
 'wrdsapps_finratio_ccm',
 'wrdsapps_finratio_ibes',
 'wrdsapps_finratio_ibes_ccm',
 'wrdsapps_link_comp_eushort',
 'wrdsapps_link_crsp_bond',
 'wrdsapps_link_crsp_factset',
 'wrdsapps_link_crsp_ibes',
 'wrdsapps_link_crsp_optionm',
 'wrdsapps_link_crsp_taq',
 'wrdsapps_link_crsp_taqm',
 'wrdsapps_link_datastream_wscope',
 'wrdsapps_link_dealscan_wscope',
 'wrdsapps_link_supplychain',
 'wrdsapps_patents',
 'wrdsapps_plink_exec_trinsider',
 'wrdsapps_subsidiary',
 'wrdsapps_windices',
 'wrdsappssamp_all',
 'wrdssec',
 'wrdssec_all',
 'wrdssec_bow',
 'wrdssec_common',
 'wrdssec_insiders',
 'wrdssec_midas',
 'wrdssec_secsa',
 'zacksamp',
 'zacksamp_all']

In [5]:
db.list_tables(library="optionm_all")

['borrate1996',
 'borrate1997',
 'borrate1998',
 'borrate1999',
 'borrate2000',
 'borrate2001',
 'borrate2002',
 'borrate2003',
 'borrate2004',
 'borrate2005',
 'borrate2006',
 'borrate2007',
 'borrate2008',
 'borrate2009',
 'borrate2010',
 'borrate2011',
 'borrate2012',
 'borrate2013',
 'borrate2014',
 'borrate2015',
 'borrate2016',
 'borrate2017',
 'borrate2018',
 'borrate2019',
 'borrate2020',
 'borrate2021',
 'borrate2022',
 'borrate2023',
 'distrd',
 'distrprojd1996',
 'distrprojd1997',
 'distrprojd1998',
 'distrprojd1999',
 'distrprojd2000',
 'distrprojd2001',
 'distrprojd2002',
 'distrprojd2003',
 'distrprojd2004',
 'distrprojd2005',
 'distrprojd2006',
 'distrprojd2007',
 'distrprojd2008',
 'distrprojd2009',
 'distrprojd2010',
 'distrprojd2011',
 'distrprojd2012',
 'distrprojd2013',
 'distrprojd2014',
 'distrprojd2015',
 'distrprojd2016',
 'distrprojd2017',
 'distrprojd2018',
 'distrprojd2019',
 'distrprojd2020',
 'distrprojd2021',
 'distrprojd2022',
 'distrprojd2023',
 'exchgd',
 'fwdprd1996',
 'fwdprd1997',
 'fwdprd1998',
 'fwdprd1999',
 'fwdprd2000',
 'fwdprd2001',
 'fwdprd2002',
 'fwdprd2003',
 'fwdprd2004',
 'fwdprd2005',
 'fwdprd2006',
 'fwdprd2007',
 'fwdprd2008',
 'fwdprd2009',
 'fwdprd2010',
 'fwdprd2011',
 'fwdprd2012',
 'fwdprd2013',
 'fwdprd2014',
 'fwdprd2015',
 'fwdprd2016',
 'fwdprd2017',
 'fwdprd2018',
 'fwdprd2019',
 'fwdprd2020',
 'fwdprd2021',
 'fwdprd2022',
 'fwdprd2023',
 'hvold1996',
 'hvold1997',
 'hvold1998',
 'hvold1999',
 'hvold2000',
 'hvold2001',
 'hvold2002',
 'hvold2003',
 'hvold2004',
 'hvold2005',
 'hvold2006',
 'hvold2007',
 'hvold2008',
 'hvold2009',
 'hvold2010',
 'hvold2011',
 'hvold2012',
 'hvold2013',
 'hvold2014',
 'hvold2015',
 'hvold2016',
 'hvold2017',
 'hvold2018',
 'hvold2019',
 'hvold2020',
 'hvold2021',
 'hvold2022',
 'hvold2023',
 'idxdvd',
 'indexd',
 'opinfd',
 'opprcd1996',
 'opprcd1997',
 'opprcd1998',
 'opprcd1999',
 'opprcd2000',
 'opprcd2001',
 'opprcd2002',
 'opprcd2003',
 'opprcd2004',
 'opprcd2005',
 'opprcd2006',
 'opprcd2007',
 'opprcd2008',
 'opprcd2009',
 'opprcd2010',
 'opprcd2011',
 'opprcd2012',
 'opprcd2013',
 'opprcd2014',
 'opprcd2015',
 'opprcd2016',
 'opprcd2017',
 'opprcd2018',
 'opprcd2019',
 'opprcd2020',
 'opprcd2021',
 'opprcd2022',
 'opprcd2023',
 'optionmnames',
 'opvold',
 'secnmd',
 'secprd',
 'secprd1996',
 'secprd1997',
 'secprd1998',
 'secprd1999',
 'secprd2000',
 'secprd2001',
 'secprd2002',
 'secprd2003',
 'secprd2004',
 'secprd2005',
 'secprd2006',
 'secprd2007',
 'secprd2008',
 'secprd2009',
 'secprd2010',
 'secprd2011',
 'secprd2012',
 'secprd2013',
 'secprd2014',
 'secprd2015',
 'secprd2016',
 'secprd2017',
 'secprd2018',
 'secprd2019',
 'secprd2020',
 'secprd2021',
 'secprd2022',
 'secprd2023',
 'securd',
 'securd1',
 'stdbrte1996',
 'stdbrte1997',
 'stdbrte1998',
 'stdbrte1999',
 'stdbrte2000',
 'stdbrte2001',
 'stdbrte2002',
 'stdbrte2003',
 'stdbrte2004',
 'stdbrte2005',
 'stdbrte2006',
 'stdbrte2007',
 'stdbrte2008',
 'stdbrte2009',
 'stdbrte2010',
 'stdbrte2011',
 'stdbrte2012',
 'stdbrte2013',
 'stdbrte2014',
 'stdbrte2015',
 'stdbrte2016',
 'stdbrte2017',
 'stdbrte2018',
 'stdbrte2019',
 'stdbrte2020',
 'stdbrte2021',
 'stdbrte2022',
 'stdbrte2023',
 'stdopd1996',
 'stdopd1997',
 'stdopd1998',
 'stdopd1999',
 'stdopd2000',
 'stdopd2001',
 'stdopd2002',
 'stdopd2003',
 'stdopd2004',
 'stdopd2005',
 'stdopd2006',
 'stdopd2007',
 'stdopd2008',
 'stdopd2009',
 'stdopd2010',
 'stdopd2011',
 'stdopd2012',
 'stdopd2013',
 'stdopd2014',
 'stdopd2015',
 'stdopd2016',
 'stdopd2017',
 'stdopd2018',
 'stdopd2019',
 'stdopd2020',
 'stdopd2021',
 'stdopd2022',
 'stdopd2023',
 'vsurfd1996',
 'vsurfd1997',
 'vsurfd1998',
 'vsurfd1999',
 'vsurfd2000',
 'vsurfd2001',
 'vsurfd2002',
 'vsurfd2003',
 'vsurfd2004',
 'vsurfd2005',
 'vsurfd2006',
 'vsurfd2007',
 'vsurfd2008',
 'vsurfd2009',
 'vsurfd2010',
 'vsurfd2011',
 'vsurfd2012',
 'vsurfd2013',
 'vsurfd2014',
 'vsurfd2015',
 'vsurfd2016',
 'vsurfd2017',
 'vsurfd2018',
 'vsurfd2019',
 'vsurfd2020',
 'vsurfd2021',
 'vsurfd2022',
 'vsurfd2023',
 'zerocd']

In [39]:
db.describe_table(library="optionm_all", table='secprd2023').sort_values(['name'])

Approximately 1668035 rows in optionm_all.secprd2023.

      name  nullable              type comment
7    cfadj      True  DOUBLE PRECISION    None
9    cfret      True  DOUBLE PRECISION    None
4    close      True  DOUBLE PRECISION    None
1     date      True              DATE    None
3     high      True  DOUBLE PRECISION    None
2      low      True  DOUBLE PRECISION    None
8     open      True  DOUBLE PRECISION    None
6   return      True  DOUBLE PRECISION    None
0    secid      True  DOUBLE PRECISION    None
10  shrout      True  DOUBLE PRECISION    None
5   volume      True  DOUBLE PRECISION    None

In [40]:
db.describe_table(library="optionm_all", table='stdopd2023').sort_values(['name'])

Approximately 21346052 rows in optionm_all.stdopd2023.

               name  nullable              type comment
11          cp_flag      True        VARCHAR(1)    None
1              date      True              DATE    None
2              days      True  DOUBLE PRECISION    None
7             delta      True  DOUBLE PRECISION    None
3     forward_price      True  DOUBLE PRECISION    None
8             gamma      True  DOUBLE PRECISION    None
6   impl_volatility      True  DOUBLE PRECISION    None
5           premium      True  DOUBLE PRECISION    None
0             secid      True  DOUBLE PRECISION    None
4      strike_price      True  DOUBLE PRECISION    None
9             theta      True  DOUBLE PRECISION    None
10             vega      True  DOUBLE PRECISION    None

In [10]:
db.describe_table(library="optionm_all", table='opprcd2023').sort_values(['name'])

Approximately 232148800 rows in optionm_all.opprcd2023.

                name  nullable              type comment
19     am_settlement      True  DOUBLE PRECISION    None
8           best_bid      True  DOUBLE PRECISION    None
9         best_offer      True  DOUBLE PRECISION    None
18             cfadj      True  DOUBLE PRECISION    None
20     contract_size      True  DOUBLE PRECISION    None
6            cp_flag      True        VARCHAR(1)    None
1               date      True              DATE    None
13             delta      True  DOUBLE PRECISION    None
4             exdate      True              DATE    None
23  expiry_indicator      True        VARCHAR(1)    None
22     forward_price      True  DOUBLE PRECISION    None
14             gamma      True  DOUBLE PRECISION    None
12   impl_volatility      True  DOUBLE PRECISION    None
5          last_date      True              DATE    None
11     open_interest      True  DOUBLE PRECISION    None
17          optionid      True  DOUBLE PRECISION    None
24              root      True        VARCHAR(5)    None
0              secid      True  DOUBLE PRECISION    None
21           ss_flag      True        VARCHAR(1)    None
7       strike_price      True  DOUBLE PRECISION    None
25            suffix      True        VARCHAR(2)    None
2             symbol      True       VARCHAR(21)    None
3        symbol_flag      True        VARCHAR(1)    None
16             theta      True  DOUBLE PRECISION    None
15              vega      True  DOUBLE PRECISION    None
10            volume      True  DOUBLE PRECISION    None

In [11]:
db.raw_sql("SELECT 0.001*0.001*COUNT(*) AS nrow_millions FROM optionm_all.opprcd2023", )

     ?column?
0  232.148794

In [13]:
db.raw_sql("SELECT * FROM optionm_all.opprcd2023 WHERE date='2023-06-14' LIMIT 6", ).transpose()

,0,1,2,3,4,5
secid,5139.0,5139.0,5139.0,5139.0,5139.0,5139.0
date,2023-06-14,2023-06-14,2023-06-14,2023-06-14,2023-06-14,2023-06-14
symbol,CAE 230616P7500,CAE 230616C10000,CAE 230616C12500,CAE 230616C15000,CAE 230616C17500,CAE 230616C20000
symbol_flag,1,1,1,1,1,1
exdate,2023-06-16,2023-06-16,2023-06-16,2023-06-16,2023-06-16,2023-06-16
last_date,None,None,None,None,2023-05-31,2023-06-13
cp_flag,P,C,C,C,C,C
strike_price,7500.0,10000.0,12500.0,15000.0,17500.0,20000.0
best_bid,0.0,9.7,7.3,4.7,2.9,0.7
best_offer,0.8,13.0,9.8,7.4,3.4,1.05
volume,0.0,0.0,0.0,0.0,0.0,0.0
open_interest,0.0,0.0,0.0,0.0,77.0,44.0
impl_volatility,NaN,8.718483,5.248846,3.702542,NaN,0.603504
delta,NaN,0.927229,0.933424,0.907454,NaN,0.808781
gamma,NaN,0.010322,0.016012,0.029128,NaN,0.293571
vega,NaN,0.212455,0.198704,0.254586,NaN,0.419005
theta,NaN,-169.6076,-95.66113,-86.73016,NaN,-23.80957
optionid,150305195.0,150305174.0,150305175.0,150305176.0,150305177.0,150305178.0
cfadj,1.0,1.0,1.0,1.0,1.0,1.0
am_settlement,0.0,0.0,0.0,0.0,0.0,0.0
contract_size,100.0,100.0,100.0,100.0,100.0,100.0
ss_flag,0,0,0,0,0,0
forward_price,None,None,None,None,None,None
expiry_indicator,None,None,None,None,None,None
root,None,None,None,None,None,None
suffix,None,None,None,None,None,None

In [8]:
ten_row = db.raw_sql(
"""
SELECT * 
FROM optionm_all.opprcd2020
WHERE symbol='SPY 200117C248000' OR symbol='SPY 200117P248000'
LIMIT 10
"""
    , )

In [9]:
ten_row.transpose()

,0,1,2,3,4,5,6,7,8,9
secid,109820.0,109820.0,109820.0,109820.0,109820.0,109820.0,109820.0,109820.0,109820.0,109820.0
date,2020-01-02,2020-01-02,2020-01-03,2020-01-03,2020-01-06,2020-01-06,2020-01-07,2020-01-07,2020-01-08,2020-01-08
symbol,SPY 200117C248000,SPY 200117P248000,SPY 200117C248000,SPY 200117P248000,SPY 200117C248000,SPY 200117P248000,SPY 200117C248000,SPY 200117P248000,SPY 200117C248000,SPY 200117P248000
symbol_flag,1,1,1,1,1,1,1,1,1,1
exdate,2020-01-17,2020-01-17,2020-01-17,2020-01-17,2020-01-17,2020-01-17,2020-01-17,2020-01-17,2020-01-17,2020-01-17
last_date,2020-01-02,2019-12-31,2020-01-02,2020-01-03,2020-01-02,2020-01-06,2020-01-02,2020-01-06,2020-01-02,2020-01-08
cp_flag,C,P,C,P,C,P,C,P,C,P
strike_price,248000.0,248000.0,248000.0,248000.0,248000.0,248000.0,248000.0,248000.0,248000.0,248000.0
best_bid,76.76,0.01,74.65,0.01,75.67,0.01,74.83,0.0,76.4,0.01
best_offer,76.96,0.02,75.14,0.02,75.91,0.02,75.12,0.01,76.64,0.02
volume,3.0,0.0,0.0,20.0,0.0,10.0,0.0,0.0,0.0,800.0
open_interest,7.0,6310.0,7.0,6310.0,7.0,6290.0,7.0,6280.0,7.0,6280.0
impl_volatility,NaN,0.461918,0.675967,0.466539,0.567728,0.532895,0.704671,0.504194,NaN,0.593868
delta,NaN,-0.00167,0.97999,-0.001722,0.997078,-0.001696,0.989861,-0.000678,NaN,-0.001679
gamma,NaN,0.000177,0.001136,0.000188,0.000281,0.000183,0.000718,0.000088,NaN,0.000179
vega,NaN,0.355542,3.055506,0.350379,0.504394,0.307441,1.446435,0.125689,NaN,0.276328
theta,NaN,-1.990729,-30.95055,-2.118774,-8.736982,-2.705656,-22.52715,-1.15547,NaN,-3.314392
optionid,124546128.0,124546174.0,124546128.0,124546174.0,124546128.0,124546174.0,124546128.0,124546174.0,124546128.0,124546174.0
cfadj,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
am_settlement,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
contract_size,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
ss_flag,0,0,0,0,0,0,0,0,0,0
forward_price,None,None,None,None,None,None,None,None,None,None
expiry_indicator,None,None,None,None,None,None,None,None,None,None
root,None,None,None,None,None,None,None,None,None,None
suffix,None,None,None,None,None,None,None,None,None,None

In [29]:
crypto_df = db.raw_sql(
"""
SELECT * 
FROM optionm_all.opprcd2023
WHERE
          (POSITION('BTC' in symbol)=1 OR POSITION('ETH' in symbol)=1)
    AND   date='2023-06-14'
"""
    , )
crypto_df.shape

(114, 26)

In [31]:
crypto_df[['Underlying', 'Desc']]=crypto_df['symbol'].str.split(" ", n=1, expand=True)

In [34]:
crypto_df[['exdate', 'Underlying', 'cp_flag', 'strike_price', 
           'best_bid', 'best_offer',  'delta', 'gamma', 'vega', 
           'volume', 'open_interest', 'impl_volatility',]]

,exdate,Underlying,cp_flag,strike_price,best_bid,best_offer,delta,gamma,vega,volume,open_interest,impl_volatility
0,2023-06-16,BTCY,C,2500.0,0.00,0.05,NaN,NaN,NaN,0.0,1105.0,NaN
1,2023-06-16,BTCY,C,5000.0,0.00,0.80,NaN,NaN,NaN,0.0,9.0,NaN
2,2023-06-16,BTCY,C,7500.0,0.00,0.05,NaN,NaN,NaN,0.0,300.0,NaN
3,2023-06-16,BTCY,P,2500.0,1.10,2.40,NaN,NaN,NaN,0.0,0.0,NaN
4,2023-06-16,BTCY,P,5000.0,2.95,5.70,NaN,NaN,NaN,0.0,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
109,2024-01-19,BTCM1,P,20000.0,19.60,20.50,NaN,NaN,NaN,0.0,0.0,NaN
110,2024-01-19,BTCM1,P,22500.0,22.10,23.00,NaN,NaN,NaN,0.0,0.0,NaN
111,2024-01-19,BTCM1,P,2500.0,2.15,2.40,NaN,NaN,NaN,0.0,10.0,NaN
112,2024-01-19,BTCM1,P,5000.0,4.60,4.90,NaN,NaN,NaN,0.0,5.0,NaN
113,2024-01-19,BTCM1,P,7500.0,7.10,7.40,NaN,NaN,NaN,0.0,2.0,NaN

In [38]:
crypto_df.groupby('Underlying')[['strike_price']].max()

            strike_price
Underlying
BTCM             10000.0
BTCM1            22500.0
BTCY              7500.0